# Generated by Django 2.2.3 on 2019-08-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TangTocQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.TextField(verbose_name='Nội dung câu hỏi')),
                ('questionField', models.CharField(choices=[('Toan', 'Toán'), ('Ly', 'Lý'), ('Hoa', 'Hoá')], max_length=50, verbose_name='Lĩnh vực')),
                ('answer', models.CharField(max_length=255, verbose_name='Đáp án')),
            ],
        ),
    ]
