# Generated by Django 2.2.3 on 2019-08-11 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tangtoc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TangTocQuestionField',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Tên lĩnh vực')),
                ('used', models.BooleanField(default=False, verbose_name='Đã sử dụng')),
            ],
        ),
        migrations.AlterField(
            model_name='tangtocquestion',
            name='questionField',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tangtoc.TangTocQuestionField', verbose_name='Lĩnh vực'),
        ),
    ]
