# Generated by Django 2.2.3 on 2019-08-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangtoc', '0002_auto_20190812_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='tangtocquestionfield',
            name='code',
            field=models.CharField(default='', max_length=30, verbose_name='Tên không dấu'),
            preserve_default=False,
        ),
    ]
