# Generated by Django 2.2.3 on 2019-08-04 18:49

from django.db import migrations, models
import khoidong.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhoiDongQuestion',
            fields=[
                ('questionID', models.IntegerField(primary_key=True, serialize=False, verbose_name='Câu hỏi số')),
                ('questionText', models.CharField(blank=True, max_length=512, verbose_name='Nội dung câu hỏi')),
                ('answer', models.CharField(max_length=256, verbose_name='Đáp án')),
                ('file', models.FileField(blank=True, upload_to=khoidong.models.questionDirectoryPath, verbose_name='File đính kèm')),
            ],
        ),
    ]
