# Generated by Django 2.2.3 on 2019-08-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khoidong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khoidongquestion',
            name='questionText',
            field=models.TextField(blank=True, verbose_name='Nội dung câu hỏi'),
        ),
    ]
