# Generated by Django 2.2.3 on 2019-08-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinhphuc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinhphucquestion',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Dễ'), ('medium', 'Trung bình'), ('hard', 'Khó')], max_length=10, verbose_name='Độ khó'),
        ),
    ]
