# Generated by Django 2.2.3 on 2019-07-28 20:59

import django.contrib.auth.models
from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('display_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Tên hiển thị')),
                ('email', models.CharField(blank=True, max_length=150)),
                ('is_contestant', models.BooleanField(default=False, verbose_name='Thí sinh?')),
                ('profile_pic', models.ImageField(blank=True, default='userprofile/default_profile.jpg', null=True, upload_to=userprofile.models.user_directory_path)),
                ('grade', models.IntegerField(blank=True, default=0, verbose_name='Điểm')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_thuky', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
