# Generated by Django 2.2.3 on 2019-08-31 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhanLuotQuestion',
            fields=[
                ('questionID', models.IntegerField(primary_key=True, serialize=False, verbose_name='Câu hỏi số')),
                ('questionText', models.TextField(blank=True, verbose_name='Nội dung câu hỏi')),
                ('answer', models.CharField(max_length=256, verbose_name='Đáp án')),
            ],
        ),
        migrations.CreateModel(
            name='PhanLuotAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phanluot.PhanLuotQuestion')),
                ('thisinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
